services:
  - type: web
    name: bharathshield
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
